# Started with https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml
version: '2'

services:
  magento_db:
    image: 'bitnami/mariadb:10.2'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    expose:
      - 3306
    volumes:
      - 'magento_db_data:/bitnami'
  magento:
    image: 'bitnami/magento:2'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=magento_db
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    expose:
      - 80
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - magento_db
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch:6'
    restart: unless-stopped
    expose:
      - 9200
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
  api_db:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - api_db_data:/data/db
    expose:
      - 27017
  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - api_db
  app:
    build: ./app
    restart: unless-stopped
    environment:
      - CHECKOUT_BRAINTREE_TOKEN=undefined
      - MAGENTO_BACKEND_URL=http://magento/
    depends_on:
      - api
  reverse_proxy:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./reverse_proxy/ssl:/etc/nginx/ssl
      - ./reverse_proxy/includes:/etc/nginx/includes
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - magento
      - app

volumes:
  elasticsearch_data:
    driver: local
  magento_db_data:
    driver: local
  magento_data:
    driver: local
  api_db_data:
    driver: local

# Options for "app" service...

######## PWA Studio Environment Variables ######################################
#
#   This file contains environment variables for a Magento PWA Studio project.
#   PWA Studio uses environment variables for all variable cross-project
#   values, so that a developer or a build system can override any variable
#   with standard tools.
#
#   This file belongs at the root of the PWA, and must be named `.env`.
#   Uncomment and modify variable declarations in this file and they will take
#   effect throughout the Buildpack tool chain.
#
#   Generated by @magento/pwa-buildpack v5.0.0 on 2020-03-31T00:40:26.223Z.
#
################################################################################

#### Connecting to a Magento store #############################################
#
#   Connect to an instance of Magento 2.3 by specifying its public domain name.
#MAGENTO_BACKEND_URL=http://magento/
#
################################################################################

#### Image Optimizing Origin ###################################################
#
#   Specify the origin to use for images in the UI. Set to `backend` when
#   Fastly or another CDN is optimizing images, and the frontend will load
#   images directly from the Magento instance at MAGENTO_BACKEND_URL. If no
#   image optimization is running on the backend, then set to `onboard`, or
#   leave blank,
#   - Default when not set: onboard
#IMAGE_OPTIMIZING_ORIGIN=onboard
#
################################################################################

#### Custom local origin #######################################################
#
#   Get or create a secure, unique hostname/port combination and a trusted SSL
#   certificate for local development.
#   - Default when not set: true
#CUSTOM_ORIGIN_ENABLED=true
#
#   Add a unique hash string to the custom origin, based on filesystem
#   location. This naturally separates domains when running multiple project
#   folders on one developer machine.
#   - Default when not set: true
#CUSTOM_ORIGIN_ADD_UNIQUE_HASH=true
#
#   Specify the subdomain prefix of the custom origin manually, instead of
#   using the package name.
#   - Default when not set:
#CUSTOM_ORIGIN_SUBDOMAIN=
#
#   Specify the exact domain of the custom origin manually.
#   - Default when not set:
#CUSTOM_ORIGIN_EXACT_DOMAIN=
#
################################################################################

#### Development server ########################################################
#
#   Specify the hostname the dev server should bind to. If this is set, it
#   overrides the host chosen by custom origin settings.
#   - Default when not set:
#DEV_SERVER_HOST=
#
#   Specify the port the dev server should bind to. If this is set, it
#   overrides the port chosen by custom origin settings.
#   - Default when not set: 0
#DEV_SERVER_PORT=
#
#   Use a service worker in developer mode (PWADevServer), which are disabled
#   in dev mode normally to simplify cache. Good for debugging.
#   - Default when not set: false
#DEV_SERVER_SERVICE_WORKER_ENABLED=
#
#   Set to a number greater than 0 to denote a polling interval in
#   milliseconds. If this is greater than 0, the dev server will use filesystem
#   polling instead of native filesystem events to watch for changes. Can
#   increase CPU usage, but sometimes is the best option for exotic filesystems
#   (e.g. NFS).
#   - Default when not set: 0
#DEV_SERVER_WATCH_OPTIONS_USE_POLLING=
#
################################################################################

#### Staging server ############################################################
#
#   Specify the hostname the staging server should bind to. If this is set, it
#   overrides the host chosen by custom origin settings.
#   - Default when not set:
#STAGING_SERVER_HOST=
#
#   Specify the port the staging server should bind to. If this is set, it
#   overrides the port chosen by custom origin settings.
#   - Default when not set: 0
#STAGING_SERVER_PORT=
#
#   Specify the id which Buildpack will put in a comment above all generated
#   bundle files and the index.html file
#   - Default when not set:
#STAGING_BUILD_ID=
#
################################################################################

#### Onboard image optimization service ########################################
#
#   Root path to mount the onboard image optimization service in the DevServer
#   and staging server.
#   - Example: /img/
#   - Default when not set: /img/
#IMAGE_SERVICE_PUBLIC_PATH=/img/
#
#   Lifetime of images in the local cache of resized images. Format is
#   "[length] [unit]", as in "10 minutes" or "1 day".
#   - Example: 5 minutes
#   - Default when not set: 1 hour
#IMAGE_SERVICE_CACHE_EXPIRES=1 hour
#
#   Log image cache debug info to the console.
#   - Default when not set: false
#IMAGE_SERVICE_CACHE_DEBUG=
#
#   To use a Redis instance instead of a local memory cache for persistence
#   between server processes, set this variable to the socket or URL of the
#   Redis instance.
#   - Default when not set:
#IMAGE_SERVICE_CACHE_REDIS_CLIENT=
#
################################################################################

#### UPWARD server settings ####################################################
#
#   UPWARD configuration file to use for the PWADevServer and the "stage:venia"
#   sample server.
#   - Default when not set: upward.yml
#UPWARD_JS_UPWARD_PATH=upward.yml
#
#   Upon launching the staging server, automatically attach to a local port and
#   listen.
#   - Default when not set: true
#UPWARD_JS_BIND_LOCAL=true
#
#   Log the bound URL to stdout once the sever is listening. Useful in testing
#   and discovery scenarios, but may be disabled in production.
#   - Default when not set: true
#UPWARD_JS_LOG_URL=true
#
################################################################################

#### Checkout and payment settings #############################################
#
#   Specify a Braintree API token to direct the Venia storefront to communicate
#   with your Braintree instance. You can find this value in Braintree's
#   Control Panel under Settings > API Keys > Tokenization Keys.
#CHECKOUT_BRAINTREE_TOKEN=undefined
#CHECKOUT_BRAINTREE_TOKEN=sandbox_8yrzsvtm_s2bg8fs563crhqzk
#
################################################################################

#### Google Maps ###############################################################
#
#   Specify a Google Maps API token for instantiating a Maps instance for your
#   Page Builder map content type.
#   - Default when not set:
#GOOGLE_MAPS_API_KEY=
#
################################################################################
